# Generated by Django 3.1.4 on 2020-12-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSNN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='probability',
            field=models.FloatField(null=True),
        ),
    ]
